### ISSUE TITLE
On the `README.md` file, you have an extra `runs-on`

### ISSUE THREAD

**Issue by gcarreno** [korandoru/setup-zig#153]
Hey @korandoru,

In the example with matrix it reads:
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
```

It should read:
```yml
jobs:
  build:
    strategy:
      fail-fast: false
```

Cheers,
Gus
